name: golang-cd

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
#  workflow_run:
#    workflows: [ "CI" ]
#    types:
#      - completed

jobs:
  cd:
    #    if: >
    #      (github.event_name == 'workflow_run' &&
    #       github.event.workflow_run.conclusion == 'success')
    #      ||
    #      (github.event_name == 'push' &&
    #       startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest

    steps:
      - name: Check repository
        uses: actions/checkout@v4

      - name: Extract version
        id: version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          echo "VERSION_TAG=${{ secrets.DOCKERHUB_REPOSITORY }}:${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          echo "LATEST_TAG=${{ secrets.DOCKERHUB_REPOSITORY }}:latest" >> $GITHUB_ENV

      - name: Print version
        run: |
          echo "VERSION:      $VERSION"
          echo "VERSION TAG:  $VERSION_TAG"
          echo "LATEST TAG:   $LATEST_TAG"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: deployments/production/Dockerfile
          push: true
          tags: |
            ${{ env.VERSION_TAG }}
            ${{ env.LATEST_TAG }}
          build-args: |
            version=${{ env.VERSION }}

      - name: Deploy to Liara
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        run: |
          npm i -g @liara/cli@7
          liara deploy \
            --app="go-pipeline" \
            --dockerfile="deployments/production/Dockerfile" \
            --api-token="$LIARA_TOKEN" \
            --port="8000" \
            --no-app-logs
