name: golang-pipeline

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          go mod tidy
          go mod download

      - name: Run Unit Tests
        run: go test ./.

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags')
    steps:
#      - uses: actions/setup-node@v3
#        with:
#          node-version: "22"

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Extract Version
        id: version_step
        run: |
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          echo "version_tag=${{ secrets.DOCKERHUB_REPOSITORY }}:${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          echo "latest_tag=${{ secrets.DOCKERHUB_REPOSITORY }}:latest" >> $GITHUB_OUTPUT

      - name: Print Version
        run: |
          echo "VERSION TAG: ${{steps.version_step.outputs.version_tag}}"
          echo "LATEST TAG:  ${{steps.version_step.outputs.latest_tag}}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare Tag Names
        run: |
          echo VERSION_TAG=$(echo ${{ steps.version_step.outputs.version_tag }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
          echo LASTEST_TAG=$(echo ${{ steps.version_step.outputs.latest_tag }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

      - name: Show directory
        run: |
          ls -la deployments/production/

      - name: Build and push on dockerhub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: deployments/production/Dockerfile
          push: true
          tags: |
            ${{env.VERSION_TAG}}
            ${{env.LASTEST_TAG}}
          build-args: |
            version=${{steps.version_step.outputs.version}}

      - name: Deploy on Liara platform
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        run: |
          node -v
          npm -v
          npm i -g @liara/cli@7
          liara deploy \
            --app="go-pipeline" \
            --dockerfile="deployments/production/Dockerfile" \
            --api-token="$LIARA_TOKEN" \
            --port="8000" \
            --no-app-logs
